### ISSUE TITLE
Click on Settings does nothing

### ISSUE THREAD

**Issue by zsubzwary** [lukeclopez/PyBallProtector#1]
First of all thank you very much, I did need something like this for a while now..... _(I found about this on Reddit)_

When ever I Right Click on the icon in the system tray menu, it shows an options for **Settings** but when I click it nothing happens !!

**Comment by lukeclopez** [comment]
Hi! I'm glad you find this useful! The settings button isn't hooked up yet. If you have any suggestions for which settings you'd like to see implemented, I'd love to hear them! I'm thinking:

- Interval time
- Notification duration
- "Forcing" mode

**Comment by zsubzwary** [comment]
Yes those features are awesome !!
